### ISSUE TITLE
Create an Architectural Diagram

### ISSUE THREAD

**Issue by ShamaKamina** [COS301-SE-2024/The-Republic#161]
We have to draw up an architectural diagram that captures the core quality requirements of our project. We have to figure out one main pattern to start with then add patterns on top as we go. Once we are done drawing a diagram we need to reach out to Stacey for confirmation. 

- We could reach out to Janco or our Mentor and ask them for advice. 
- Do some research on what's the best architecture for our project.

**Comment by TebogoYungMercykay** [comment]
Created.
