### ISSUE TITLE
Add tests for backend repositories

### ISSUE THREAD

**Issue by MulisaMusehane** [COS301-SE-2024/The-Republic#193]
The following backend repositories have insufficient test coverage. This issue aims to improve the coverage to ensure better reliability and maintainability.

Checkpoints:

- [ ] categoryRepository.ts: Coverage is currently at 37.5%. Targeting lines 6-22.
- [ ] commentRepository.ts: Coverage is currently at 9.67%. Targeting lines 8-141.
- [ ] issueRepository.ts: Coverage is currently at 8.08%. Targeting lines 16-599.
- [ ] locationRepository.ts: Coverage is currently at 13.04%. Targeting lines 16-81.
- [ ] reactionRepository.ts: Coverage is currently at 9.37%. Targeting lines 7-105.
- [ ] reportsRepository.ts: Coverage is currently at 3.22%. Targeting lines 8-285.
- [ ] userRepository.ts: Coverage is currently at 14.28%. Targeting lines 7-81.
- [ ] visualizationRepository.ts: Coverage is currently at 13.63%. Targeting lines 8-52.

**Comment by TebogoYungMercykay** [comment]
@hlokomani suggested that we test only the Controller and Service layers since that's where the heavy lifting is. The Repository layer (db) contains only queries, which would fail to execute if there were any issues, so we do not need to test it from what he said, that's if I'm not mistaken.

**Comment by MulisaMusehane** [comment]
Thanks for the heads up - I’ll take that into account and close this ticket. 🎟️ @hlokomani can I close it?
