### ISSUE TITLE
Create use case diagrams

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#3]
Use the subsystems in the RequirementsSpecification.md to draw out the use cases - how the user interacts with each subsystem.
Add the images in the RequirementsSpecification.md under the Use Case Diagrams heading.

**Comment by MulisaMusehane** [comment]
Use the subsystems in the RequirementsSpecification.md to draw out the use cases - how the user interacts with each subsystem.
Add the images in the RequirementsSpecification.md under the Use Case Diagrams heading.
