### ISSUE TITLE
Complete setting up CI/CD pipeline with Github actions

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#30]
- Complete the deployment for the backend server to Heroku and the frontend to vercel/heroku and also Integrate unit tests with GitHub jobs, fix linter "imports" issue. 
- The issue we experiencing is that with the current deployment for heroku, the whole repository source code is deployed and only the backend folder is needed, We need to fin a way to deploy only the specific folders.
- This code snippets do show an example but we haven't tested them yet: [Example Code](https://stackoverflow.com/questions/74280172/how-to-run-a-github-action-only-on-a-specified-folder)

**Comment by TebogoYungMercykay** [comment]
I am left with testing The Hosting Jobs for the Frontend as well as Backend, I am awaiting the access token to test them thoroughly as well as the Job for the code formatter.
