### ISSUE TITLE
Add a landing page 

### ISSUE THREAD

**Issue by MulisaMusehane** [COS301-SE-2024/The-Republic#317]
### Hero Section
- **Task**: Design a hero section with the following elements:
  - A brief and impactful tagline summarizing The Republic’s mission to revolutionize citizen engagement with government services.
  - Include a call-to-action (CTA) button such as **"Get Started"** or **"Join the Conversation"** to encourage user engagement.

### Project Overview
- **Task**: Write a short paragraph summarizing the purpose of the platform:
  
  > "The Republic project aims to revolutionize citizen engagement with government services by providing a platform for individuals to share their experiences, report incidents, and voice their concerns. This initiative enhances transparency and accountability within government operations."

### Core Features
- **Task**: List and briefly describe key features of The Republic platform:
  - **Incident Reporting**: Allow users to report incidents related to government services.
  - **Data Analysis**: Provide tools to analyze reported data for insights.
  - **Public Discourse**: Enable meaningful discussions and feedback on government operations. etc etc etc.

### Visuals
- **Task**: Add engaging visuals (e.g., icons, images) that represent the core features listed above.

### Call to Action Section
- **Task**: Design a section encouraging users to sign up or explore the platform further, featuring a clear CTA button like **"Sign Up"** or **"Explore More"**.

### Footer
- **Task**: Add a footer section with:
  - Links to social media platforms.
  - Contact information for support or inquiries.
  - Links to relevant GitHub repositories for the project.

### Inspiration
![image](https://github.com/user-attachments/assets/6376dc1e-ed64-4732-bfc3-0efaff6eaa74)
https://dribbble.com/search/website-landing-page

**Comment by hlokomani** [comment]
Could we place the link to the about page on the right side bar, sort of like where twitter places their other information:
![image](https://github.com/user-attachments/assets/036cf02f-3e6b-470e-9cb3-3c73f4d9ce34)
![image](https://github.com/user-attachments/assets/3f0df2ee-ce0a-49e6-a282-0b6482f09325)

obviously our text should be a bit bigger, but hope you get the idea.
