### ISSUE TITLE
Make a deployment diagram

### ISSUE THREAD

**Issue by ShamaKamina** [COS301-SE-2024/The-Republic#381]
- A deployment diagram is similar to an architectural diagram except this time we mention the technology we used. 

- We need to make one and add it to our docs

References
https://en.wikipedia.org/wiki/Deployment_diagram
https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-deployment-diagram/#:~:text=Deployment%20diagrams%20is%20a%20kind,(topology%20of%20the%20hardware).

**Comment by TebogoYungMercykay** [comment]
Closed By [PR](https://github.com/COS301-SE-2024/The-Republic/pull/392)
