### ISSUE TITLE
Add The MIssing Expectations for Demo 1 Specs

### ISSUE THREAD

**Issue by TebogoYungMercykay** [COS301-SE-2024/The-Republic#53]
# List Of Expectations Yet To Be Added

### GitHub Landing Page (README) Requirements:

- [x] Code Coverage — Coveralls, Codecov, SonarCloud
- [x] A link to a recorded demo video named `InfiniteLoopers-Demo1`
- [x] A link to our GitHub Project Board - Project management tool

### To Be Shown On Our GitHub Repository:

- [x] Monitoring — NodePing, PingPong, Security Headers, Uptime Robot
- [x] Requirements — requires.io

### Slideshow edits
- [x] Add screenshot of Github actions running to the canva slideshow

**Comment by hlokomani** [comment]
Link to the recorded demo https://drive.google.com/drive/u/1/folders/1avytjZQfRpxRIAfVBcHBe6nfeHPmlbXi @TebogoYungMercykay
