### ISSUE TITLE
Review current documentation and make sure it is up to date

### ISSUE THREAD

**Issue by hlokomani** [COS301-SE-2024/The-Republic#59]
We must look through all the documentation we have and see:
- Which ones need to be updated?
- Which ones must be worked on between now and the next demo?
- Does our documentation match what we have implemented or plan to implement?

This ticket will require you to go through the code that we have and ensure what it does is reflected in our documentation

**Comment by TebogoYungMercykay** [comment]
I updated some of the documentation just now. Please check them and let me know if I need to add/remove something.
