### ISSUE TITLE
Implement a Help Menu

### ISSUE THREAD

**Issue by ShamaKamina** [COS301-SE-2024/The-Republic#69]
The Help Menu is an in-product help menu, a self-serve support module embedded within the product. It helps users navigate the product through quick access to valuable resources. It should include relevant links to the help center, tutorials, and top FAQs. 

### Sub tasks

- [ ] Give an overview of what users can find in the help menu
- [ ] Add a search bar to allow users to search for specific help topics or keywords
- [ ] Group help topics into logical categories e.g "Getting Started", "Account Management" and "Troubleshooting"
- [ ] Allow users to expand ot collapse sections for easier navigation
- [ ] Add a list of FAQ with answers
- [ ] Add tutorials and guides 

Helpful Documentation
https://www.chameleon.io/blog/help-menu-design
https://developers.hubspot.com/docs/cms/building-blocks/menus-and-navigation

Example screenshot
![image](https://github.com/COS301-SE-2024/The-Republic/assets/62930548/5a2583c0-a96c-4f3c-a713-f662379ab34e)

**Comment by hlokomani** [comment]
Really good idea, nice one.
